import csv
import hashlib
import shutil
import subprocess
import zipfile
from pathlib import Path

import pandas as pd
from docx import Document
from docx.enum.section import WD_ORIENT, WD_SECTION
from docx.enum.style import WD_STYLE_TYPE
from docx.enum.table import WD_CELL_VERTICAL_ALIGNMENT
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Inches, Pt, RGBColor
from pptx import Presentation
from pptx.enum.text import PP_ALIGN
from pptx.util import Inches as PptxInches
from pptx.util import Pt as PptxPt


ROOT = Path(__file__).resolve().parents[1]
MANUSCRIPT = ROOT / "manuscript"
SUPPLEMENT = ROOT / "supplement"
SUBMISSION = ROOT / "submission"
SUBMISSION_FINAL = ROOT / "submission_final"
FIGURES = ROOT / "figures"
TABLES = ROOT / "tables"

TITLE = (
    "Identifiability of spatial relations under geodetic datum "
    "and reference-frame loss"
)
SHORT_TITLE = "Spatial relations under datum loss"
AUTHOR = "Tatsuki Onishi"
AFFILIATION = "[Affiliation to be confirmed]"
EMAIL = "bougtoir@gmail.com"
PUBLIC_REPOSITORY_URL = "https://github.com/bougtoir/deep-time-reference-systems"
AUTHOR_CONTRIBUTIONS = (
    "Tatsuki Onishi: Conceptualization, methodology, validation, formal analysis, "
    "investigation, data curation, writing—original draft, writing—review and editing, "
    "visualization, supervision, and project administration."
)
DATA_AVAILABILITY = (
    "The persisted ITRF2020 SLR source file, its checksum ledger, the processed station "
    "selection, simulation configurations, and generated numerical results are available "
    f"in the public repository at {PUBLIC_REPOSITORY_URL}. The authoritative ITRF source "
    "is https://itrf.ign.fr/ftp/pub/itrf/itrf2020/ITRF2020_SLR.SSC.txt."
)
CODE_AVAILABILITY = (
    "The complete reproducible Python analysis and document-generation pipeline, pinned "
    f"configuration, tests, and reproducibility archive are available at "
    f"{PUBLIC_REPOSITORY_URL}."
)
AI_DISCLOSURE = (
    "During preparation of this work, the author used the Devin web service by Cognition "
    "(no user-visible version identifier; used 24–25 September 2026). Prompts requested "
    "targeted literature-metadata verification, Python implementation and checking, "
    "deterministic simulation replication, figure/table/document generation, numerical "
    "reconciliation, and language revision. The tool assisted with those tasks but did "
    "not supply empirical source data or generate experimental images; all numerical "
    "results and display items were regenerated by the disclosed code from persisted "
    "inputs and configurations. The author reviewed and verified the code, outputs, "
    "references, figures, and text, made the scientific and editorial decisions, and "
    "takes full responsibility for the content."
)


def figure_captions(values: dict[str, float]) -> list[str]:
    return [
        "Preserved observables and the spatial meaning they support. Each layer adds "
        "information not recoverable from the preceding layer under the stated "
        "Euclidean model.",
        "Residual invariance group after successive physical anchors. Complete centered "
        "Euclidean chord distances leave O(3); a directed axis leaves O(2); an "
        "independently recoverable physical chiral witness leaves SO(2); and a "
        "directed meridian removes the final axial rotation.",
        "Directional asymmetry under axial reflection. Generic axial-latitude ordering "
        "is preserved, whereas signed relative longitude reverses. The longitude "
        "relation is pairwise on the principal branch and is undefined at axis and "
        "projected-antipode degeneracies.",
        "Probability of full local rigidity for generic three-dimensional random "
        "frameworks. Each cell summarizes "
        f"{int(values['rigidity_trials_per_cell'])} independently sampled point-and-edge "
        "realizations after the six infinitesimal Euclidean gauge modes are removed. "
        "The result concerns local rigidity, not global uniqueness.",
        "ITRF2020 demonstration. The left panel shows the selected SLR sites and "
        "published velocity magnitudes. The right panel shows absolute pairwise "
        "Euclidean chord-distance changes after linear propagation from epoch "
        f"{values['reference_epoch']:.1f} to {values['comparison_epoch']:.1f}; this is "
        "an epoch-sensitivity calculation, not a reflected physical realization.",
    ]


def metric_values() -> dict[str, float]:
    frame = pd.read_csv(ROOT / "results/manuscript_values.csv")
    return dict(zip(frame["metric"], frame["value"]))


def number(value: float, digits: int = 3) -> str:
    if abs(value) >= 1000:
        return f"{value:,.0f}"
    return f"{value:.{digits}f}"


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def set_repeat_table_header(row) -> None:
    row_properties = row._tr.get_or_add_trPr()
    repeat = OxmlElement("w:tblHeader")
    repeat.set(qn("w:val"), "true")
    row_properties.append(repeat)


def style_document(document: Document) -> None:
    section = document.sections[0]
    section.top_margin = Inches(0.8)
    section.bottom_margin = Inches(0.8)
    section.left_margin = Inches(0.9)
    section.right_margin = Inches(0.9)
    normal = document.styles["Normal"]
    normal.font.name = "Times New Roman"
    normal.font.size = Pt(11)
    normal.paragraph_format.line_spacing = 1.25
    normal.paragraph_format.space_after = Pt(6)
    for name in ["Title", "Heading 1", "Heading 2", "Heading 3"]:
        style = document.styles[name]
        style.font.name = "Arial"
        style.font.color.rgb = RGBColor(31, 65, 89)
    document.styles["Title"].font.size = Pt(18)
    document.styles["Heading 1"].font.size = Pt(14)
    document.styles["Heading 2"].font.size = Pt(12)
    if "Equation" not in [style.name for style in document.styles]:
        equation = document.styles.add_style("Equation", WD_STYLE_TYPE.PARAGRAPH)
        equation.font.name = "Cambria Math"
        equation.font.size = Pt(11)
        equation.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.CENTER
        equation.paragraph_format.space_before = Pt(6)
        equation.paragraph_format.space_after = Pt(6)
    footer = section.footer.paragraphs[0]
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer.add_run(SHORT_TITLE)


def add_title_page(document: Document) -> None:
    paragraph = document.add_paragraph(style="Title")
    paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
    paragraph.add_run(TITLE)
    author = document.add_paragraph()
    author.alignment = WD_ALIGN_PARAGRAPH.CENTER
    author.add_run(AUTHOR).bold = True
    affiliation = document.add_paragraph()
    affiliation.alignment = WD_ALIGN_PARAGRAPH.CENTER
    affiliation.add_run(AFFILIATION)
    correspondence = document.add_paragraph()
    correspondence.alignment = WD_ALIGN_PARAGRAPH.CENTER
    correspondence.add_run(f"Correspondence: {EMAIL}")
    article_type = document.add_paragraph()
    article_type.alignment = WD_ALIGN_PARAGRAPH.CENTER
    article_type.add_run("Original Research Article — Journal of Geodesy")


def add_figure(
    document: Document,
    figure_number: int,
    captions: list[str],
) -> None:
    name = [
        "",
        "representation_hierarchy.png",
        "residual_invariance_hierarchy.png",
        "direction_asymmetry.png",
        "rigidity_phase_diagram.png",
        "itrf_demonstration.png",
    ][figure_number]
    image = FIGURES / f"figure_{figure_number}_{name}"
    paragraph = document.add_paragraph()
    paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
    paragraph.paragraph_format.space_before = Pt(10)
    paragraph.add_run().add_picture(str(image), width=Inches(6.25))
    caption = document.add_paragraph()
    caption.paragraph_format.space_before = Pt(14)
    caption.paragraph_format.space_after = Pt(10)
    caption.add_run(f"Fig. {figure_number}  ").bold = True
    caption.add_run(captions[figure_number - 1])


def add_dataframe_table(
    document: Document,
    frame: pd.DataFrame,
    table_number: int | str,
    caption_text: str,
) -> None:
    caption = document.add_paragraph()
    caption.paragraph_format.space_before = Pt(14)
    caption.add_run(f"Table {table_number}  ").bold = True
    caption.add_run(caption_text)
    table = document.add_table(rows=1, cols=len(frame.columns))
    table.style = "Table Grid"
    table.autofit = True
    for index, column in enumerate(frame.columns):
        table.rows[0].cells[index].text = column.replace("_", " ").title()
        table.rows[0].cells[index].vertical_alignment = WD_CELL_VERTICAL_ALIGNMENT.CENTER
        for run in table.rows[0].cells[index].paragraphs[0].runs:
            run.bold = True
            run.font.size = Pt(8)
    set_repeat_table_header(table.rows[0])
    for row in frame.itertuples(index=False):
        cells = table.add_row().cells
        for index, value in enumerate(row):
            cells[index].text = str(value)
            cells[index].vertical_alignment = WD_CELL_VERTICAL_ALIGNMENT.CENTER
            for run in cells[index].paragraphs[0].runs:
                run.font.size = Pt(8)


def add_landscape_section(document: Document) -> None:
    section = document.add_section(WD_SECTION.NEW_PAGE)
    section.orientation = WD_ORIENT.LANDSCAPE
    section.page_width, section.page_height = section.page_height, section.page_width
    section.top_margin = Inches(0.6)
    section.bottom_margin = Inches(0.6)
    section.left_margin = Inches(0.6)
    section.right_margin = Inches(0.6)


def add_portrait_section(document: Document) -> None:
    section = document.add_section(WD_SECTION.NEW_PAGE)
    section.orientation = WD_ORIENT.PORTRAIT
    section.page_width, section.page_height = section.page_height, section.page_width
    section.top_margin = Inches(0.8)
    section.bottom_margin = Inches(0.8)
    section.left_margin = Inches(0.9)
    section.right_margin = Inches(0.9)


def add_reference(document: Document, text: str) -> None:
    paragraph = document.add_paragraph(text)
    paragraph.paragraph_format.left_indent = Inches(0.25)
    paragraph.paragraph_format.first_line_indent = Inches(-0.25)
    paragraph.paragraph_format.space_after = Pt(4)


def manuscript_sections(values: dict[str, float]) -> tuple[str, list[tuple[str, list[str]]]]:
    rigidity = pd.read_csv(ROOT / "results/rigidity_phase_diagram.csv")
    rigidity_sizes = ", ".join(str(value) for value in sorted(rigidity["n_points"].unique()))
    rigidity_probabilities = ", ".join(
        f"{value:.1f}" for value in sorted(rigidity["edge_probability"].unique())
    )
    abstract = (
        "Geodetic coordinates are interpretable only through a datum or reference "
        "frame, its realization, and epoch. We ask which spatial relations remain "
        "identifiable when that metadata is lost, a question distinct from estimating "
        "coordinates in a free network. For centered three-dimensional configurations "
        "with known metric scale, complete labeled Euclidean chord distances leave a "
        "residual O(3) invariance group. An independently interpreted directed axis "
        "reduces this to "
        "O(2), a physically recoverable chiral witness reduces it to SO(2), and an "
        "independently recoverable directed meridian removes the residual rotation. "
        "Thus an axis alone does not select signed relative longitude, and a stored "
        "orientation bit is sufficient only if its physical interpretation is "
        "independently recoverable. We test this hierarchy with seeded distance-geometry "
        "simulations, generic incomplete random frameworks, WGS84–GRS80 sensitivity, "
        "and an ITRF2020 satellite-laser-ranging demonstration. For "
        f"{int(values['rigidity_largest_network_n_points'])}-point random "
        "frameworks, the first tested edge-retention probability with observed full-"
        "local-rigidity frequency at least 0.95 was "
        f"{values['rigidity_95pct_threshold_edge_probability']:.1f}, where the estimated "
        "frequency was "
        f"{values['rigidity_probability_at_95pct_threshold']:.3f}; this does not "
        "establish global rigidity. "
        "Changing WGS84 to GRS80 altered synthetic chord distances by at most "
        f"{values['ellipsoid_maximum_chord_distance_difference_m']:.6f} m without "
        "changing directional classifications. In the ITRF2020 network, linear "
        f"propagation from {values['reference_epoch']:.1f} to "
        f"{values['comparison_epoch']:.1f} changed pairwise chord distances by a maximum "
        f"of {values['maximum_pairwise_distance_change_m']:.3f} m and a median of "
        f"{values['median_pairwise_distance_change_m']:.3f} m. The framework identifies "
        "which archival claims are invariant, which require physical anchors, and which "
        "must remain explicitly ambiguous."
    )
    sections = [
        (
            "1 Introduction",
            [
                (
                    "A geodetic coordinate tuple is not a physical location by itself. "
                    "Its interpretation depends on a coordinate reference system, datum "
                    "or reference-frame realization, coordinate epoch, and coordinate "
                    "operations (ISO 2019; Petit and Luzum 2010). Terrestrial reference "
                    "frames realize origin, scale, orientation, and time evolution from "
                    "observations and conventions (Altamimi et al. 2002, 2023). Numeric "
                    "coordinates and trajectory models remain epoch- and model-dependent "
                    "(Bevis and Brown 2014), yet can outlive the metadata, station "
                    "realization, software, or object identifiers needed to interpret them."
                ),
                (
                    "Datum defects, rank-deficient normal equations, free-network "
                    "adjustment, inner constraints, and minimum constraints are "
                    "established geodetic topics (Papo 1985; Sillard and Boucher 2001; "
                    "Kotsakis 2012, 2013; Kotsakis and Chatzinikos 2017). Coordinate-"
                    "invariant network models clarify which parameters are non-estimable "
                    "before a datum is imposed (Chatzinikos and Dermanis 2017), while "
                    "no-net-rotation and station-selection choices affect realized frames "
                    "(Altamimi et al. 2003; Glaser et al. 2015; Zajdel et al. 2019)."
                ),
                "__FIGURE_1__",
                (
                    "Our question begins after that operational setting has failed: given "
                    "only selected archived observables, which relational claims remain "
                    "identifiable, and what residual invariance group remains? We focus "
                    "on labeled "
                    "Euclidean chord distances, axial ordering, signed relative longitude, "
                    "and absolute angular origin. Fig. 1 separates the information "
                    "layers. This is a sufficiency audit for archival observables, not a "
                    "new datum-adjustment method."
                ),
                (
                    "The contribution is threefold: a corrected residual-invariance "
                    "hierarchy that separates axis, physical chirality, and meridian "
                    "information; explicit "
                    "definitions and degeneracy states for directional relations; and a "
                    "reproducible analysis of incomplete-network local rigidity, ellipsoid "
                    "sensitivity, and epoch dependence in an ITRF2020 example. The "
                    "synthetic reflection and corruption experiments serve as theorem "
                    "validation rather than as empirical discoveries."
                ),
            ],
        ),
        (
            "2 Geodetic observables and terminology",
            [
                (
                    "We follow IERS usage: a terrestrial reference system is the "
                    "theoretical specification, whereas a terrestrial reference frame "
                    "is its realization by coordinates and motions of physical points "
                    "(Petit and Luzum 2010; Altamimi et al. 2023). A datum, coordinate "
                    "reference system, and coordinate operation are metadata needed to "
                    "interpret coordinate values, but none is identical to the physical "
                    "relation being archived. An ellipsoid such as GRS80 specifies shape "
                    "and gravity-related constants, not a complete time-evolving frame "
                    "(Moritz 2000)."
                ),
                (
                    "The theoretical distance is d_ij = ||x_i - x_j||_2 in a "
                    "three-dimensional Euclidean embedding: a chord distance, not a "
                    "surface geodesic on a sphere or ellipsoid. Surface-geodesic distance "
                    "defines a different distance-geometry problem and is outside the "
                    "present theorems."
                ),
                (
                    "For a nonzero directed axis s and nonzero point x measured from a "
                    "specified origin, define generic axial latitude as "
                    "phi_s(x) = asin[(s·x)/(||s||||x||)]. This becomes geocentric latitude "
                    "only when the origin and directed axis have the corresponding "
                    "terrestrial interpretation. It is not geodetic latitude, which uses "
                    "the ellipsoid normal; astronomical latitude, which uses the local "
                    "gravity direction; or magnetic latitude, which uses a magnetic-field "
                    "model. We use north/south only when the directed axis has an "
                    "independently defined physical interpretation."
                ),
                (
                    "For projections a_perp and b_perp onto the plane normal to s, define "
                    "signed relative longitude by atan2[s·(b_perp × a_perp), "
                    "a_perp·b_perp] on the principal branch (-pi, pi]. The relation is "
                    "pairwise and is not a globally transitive total order. It is reported "
                    "as undefined for axis projections and exact or near projected "
                    "antipodes; same-meridian pairs are explicit ties. Branch-cut "
                    "proximity is therefore a conditioning issue, not hidden by a forced "
                    "east/west label."
                ),
                (
                    "We represent an archived relation event as E = {I, t_obs, t_ref, G, "
                    "O, C, M, U, P}. I stores entity identifiers and identity hypotheses; "
                    "t_obs and t_ref are observation and reference epochs; G is relational "
                    "geometry; O contains origin and directed-axis information; C is a "
                    "physically interpretable chiral witness; M is a directed meridian or "
                    "equivalent angular anchor; U is uncertainty; and P records provenance "
                    "and model assumptions. Entity identity and epoch recoverability are "
                    "independent of geometric precision."
                ),
            ],
        ),
        (
            "3 Identifiability theory",
            [
                (
                    "Let X = [x_1, ..., x_n]^T be labeled points in R^3 and let D contain "
                    "d_ij = ||x_i - x_j||. Double centering of squared distances gives "
                    "B = -1/2 J(D∘D)J, where J = I - 11^T/n. An eigendecomposition of B "
                    "recovers centered coordinates whenever D is Euclidean. For a generic "
                    "rank-three configuration, any other realization with the same D is "
                    "XQ + 1c^T for orthogonal Q and translation c. If physical units are "
                    "not stored, a scale factor is also free (Dokmanić et al. 2015; "
                    "Liberti et al. 2014)."
                ),
                (
                    "For a retained observable map F, we call the transformations Q for "
                    "which F(QX) = F(X) the residual invariance group of those "
                    "observables. This is an observational equivalence group, not the "
                    "pointwise stabilizer of a generic realized configuration."
                ),
                (
                    "Proposition 1 (metric identifiability). For a generic complete "
                    "labeled Euclidean distance matrix of embedding dimension three, "
                    "the realization is unique only modulo translation and an element "
                    "of O(3). Proof sketch: double centering determines the centered "
                    "Gram matrix. Any rank-three factorization of that Gram matrix "
                    "differs by an orthogonal factor. Because O(3) contains both proper "
                    "and improper transformations, distance data do not select chirality."
                ),
                (
                    "After translation is removed and metric scale is known, the residual "
                    "invariance group is O(3). Requiring an independently interpreted "
                    "directed axis s leaves an O(2) residual invariance group because "
                    "axial reflections remain. A physically recoverable chiral witness "
                    "selects the proper branch and leaves SO(2), the rotations about s. An "
                    "independently recoverable directed meridian removes that final "
                    "rotation. Fig. 2 and Table 1 summarize the chain "
                    "O(3) -> O(2) -> SO(2) -> {I}."
                ),
                "__FIGURE_2__",
                "__TABLE_1__",
                (
                    "Proposition 2 (axial-order invariance). Let Q be any orthogonal "
                    "transformation applied jointly to centered points and directed axis. "
                    "Because (Qs)·(Qx) = s·x and norms are preserved, axial latitude and "
                    "its pairwise ordering are invariant under both proper and improper "
                    "transformations. The directed sense is essential: replacing s by -s "
                    "exchanges the ordering."
                ),
                (
                    "Proposition 3 (chirality dependence). Under the same joint "
                    "orthogonal transformation, the scalar triple product defining the "
                    "sine term is multiplied by det(Q), whereas the cosine term is "
                    "unchanged. Signed relative longitude is therefore invariant under "
                    "SO(3) and reverses under an axial reflection in O(3)\\SO(3), as "
                    "illustrated in Fig. 3. An algebraic orientation label resolves this "
                    "ambiguity only if the physical interpretation of the label is "
                    "independently recoverable; a coordinate-handedness convention alone "
                    "is not a physical witness."
                ),
                "__FIGURE_3__",
                (
                    "Proposition 4 (meridian necessity). With origin, directed axis, "
                    "and physical chirality fixed, every proper rotation about s preserves "
                    "distances, axial ordering, and signed relative longitudes. These "
                    "observables cannot identify an absolute angular origin. A directed "
                    "meridian or equivalent oriented external direction at the relevant "
                    "epoch is required. Without physical chirality, axis plus meridian "
                    "still leaves the reflection fixing both."
                ),
                (
                    "These statements concern identifiability, not necessarily stable "
                    "estimation. Identifiability asks whether two admissible states can "
                    "produce exactly the same retained information; conditioning asks how "
                    "strongly noise in that information changes an estimate. A nearly "
                    "coplanar oriented simplex may formally encode chirality while being "
                    "numerically fragile. The archive must therefore store uncertainty "
                    "and quality indicators for anchors rather than only a categorical "
                    "claim that an anchor exists."
                ),
                (
                    "For incomplete distance graphs, local rigidity of a generic "
                    "three-dimensional framework requires rigidity-matrix rank 3n - 6 "
                    "(Asimow and Roth 1978, 1979). This rank condition removes the six "
                    "infinitesimal Euclidean gauge motions but does not establish global "
                    "rigidity or exclude disconnected noncongruent realizations. It is "
                    "therefore used here as a limited network-identifiability diagnostic."
                ),
            ],
        ),
        (
            "4 Materials and methods",
            [
                (
                    "The synthetic benchmark samples 24 points on a WGS84-shaped "
                    "ellipsoid, forms the complete distance matrix, and reconstructs a "
                    "three-dimensional configuration by classical multidimensional "
                    "scaling. Proper and reflection-permitting Procrustes fits are "
                    "computed independently from the same unaligned reconstruction using "
                    "the determinant constraint of Kabsch (1976, 1978)."
                ),
                (
                    f"{int(values['synthetic_frame_trials'])} random proper rotations and "
                    "axial reflections validate the directional invariance claims. "
                    f"{int(values['synthetic_monte_carlo_trials_per_condition'])} Monte "
                    "Carlo trials per condition perturb the axis and corrupt an algebraic "
                    "orientation label; these are symmetry sanity checks, not models of "
                    "physical witness survival. Wilson intervals quantify finite-"
                    "simulation uncertainty. The frame taxonomy in Table 2 distinguishes "
                    "the physical meaning and failure modes of candidate anchors."
                ),
                "__TABLE_2__",
                (
                    "The incomplete-network experiment draws generic points from a "
                    "continuous three-dimensional distribution for n = "
                    f"{rigidity_sizes}. Every possible edge is retained independently "
                    "with probability in "
                    f"{{{rigidity_probabilities}}}, with "
                    f"{int(values['rigidity_trials_per_cell'])} point-and-graph trials "
                    "per cell. We calculate "
                    "the numerical rigidity-matrix rank, full-local-rigidity frequency, "
                    "Wilson interval, and excess nullity after the six Euclidean gauge "
                    "modes. Table 3 reports the first tested edge-retention probabilities "
                    "with observed local-rigidity frequencies at or above 0.50 and 0.95; "
                    "it is a seeded phase diagram, not a universal threshold."
                ),
                "__TABLE_3__",
                (
                    "Ellipsoid sensitivity compares WGS84 with GRS80 using identical "
                    "seeded geodetic latitudes and longitudes. We report coordinate and "
                    "chord-distance differences and agreement of axial-order and signed-"
                    "longitude classifications. This isolates dependence on the reference "
                    "ellipsoid from the group-theoretic claims."
                ),
                (
                    "For a realized geodetic demonstration, we parse the official "
                    "ITRF2020 SLR station file at reference epoch "
                    f"{values['reference_epoch']:.1f} (Altamimi et al. 2023). Stations "
                    "with maximum Cartesian coordinate standard uncertainty no greater "
                    f"than {values['maximum_coordinate_standard_uncertainty_m']:.2f} m "
                    "are divided into longitude bins; "
                    "the best station in each occupied bin is selected and supplemented "
                    "from remaining eligible stations to obtain "
                    f"{int(values['n_selected_sites'])} sites. Positions are linearly "
                    f"propagated to {values['comparison_epoch']:.1f} using published "
                    "velocities. This "
                    "propagation is an epoch-sensitivity demonstration, not a complete "
                    "nonlinear station-motion model."
                ),
                (
                    "Epoch sensitivity can be written schematically as x(t) = x(t_ref) + "
                    "v(t - t_ref) + d(t), where v is a secular velocity and d contains "
                    "discontinuities, seasonal signals, postseismic deformation, and "
                    "other nonlinear terms. Dropping t_ref or the motion model makes a "
                    "coordinate internally incomplete. Our "
                    f"{values['comparison_epoch'] - values['reference_epoch']:.0f}-year "
                    "linear calculation "
                    "retains only the secular term so that the role of epoch is visible "
                    "without conflating it with a station-specific geophysical model."
                ),
                (
                    "All reported numerical values are loaded from the generated result "
                    "registry rather than copied into the document builder. Calculations "
                    f"use seed {int(values['random_seed'])}. Raw-input checksums, "
                    "acquisition metadata, result "
                    "traceability, code, tests, editable tables, and editable figure "
                    "slides accompany the submission."
                ),
            ],
        ),
        (
            "5 Results",
            [
                (
                    "The incomplete-network analysis produced a size-dependent transition "
                    "in local rigidity (Fig. 4). For n = "
                    f"{int(values['rigidity_largest_network_n_points'])}, full local "
                    "rigidity occurred in "
                    f"{values['rigidity_probability_before_95pct_threshold']:.3f} of "
                    "trials at edge-retention probability "
                    f"{values['rigidity_edge_probability_before_95pct_threshold']:.1f} "
                    "(95% Wilson interval "
                    f"{values['rigidity_probability_before_95pct_threshold_95ci_lower']:.3f}"
                    "–"
                    f"{values['rigidity_probability_before_95pct_threshold_95ci_upper']:.3f}) "
                    f"and {values['rigidity_probability_at_95pct_threshold']:.3f} at "
                    f"{values['rigidity_95pct_threshold_edge_probability']:.1f}. "
                    "The latter 95% Wilson interval was "
                    f"{values['rigidity_95pct_threshold_95ci_lower']:.3f}–"
                    f"{values['rigidity_95pct_threshold_95ci_upper']:.3f}. "
                    "The first tested probability with an observed frequency at least "
                    "0.95 was therefore "
                    f"{values['rigidity_95pct_threshold_edge_probability']:.1f}. "
                    "Smaller frameworks required higher tested retention probabilities "
                    "(Table 3). These frequencies characterize the configured random "
                    "framework ensemble and do not imply global rigidity."
                ),
                "__FIGURE_4__",
                (
                    "Replacing WGS84 by GRS80 changed synthetic coordinates by at most "
                    f"{values['ellipsoid_maximum_coordinate_difference_m']:.6f} m and "
                    "Euclidean chord distances by at most "
                    f"{values['ellipsoid_maximum_chord_distance_difference_m']:.6f} m. "
                    "Both axial-order and signed-longitude classifications agreed for all "
                    "tested pairs. The sensitivity values are reported in Supplementary "
                    "Table S1."
                ),
                (
                    "The complete distance matrix reconstructed the synthetic "
                    f"configuration with a reflection-permitting RMSE of "
                    f"{values['distance_reconstruction_rmse_allow_reflection_m']:.2e} "
                    "m. For the seeded realization, constraining the alignment to a proper "
                    f"rotation exposed an RMSE of "
                    f"{number(values['distance_reconstruction_rmse_proper_only_m'] / 1e6, 3)} "
                    "million m, demonstrating that a numerically exact metric recovery "
                    "need not recover handed orientation."
                ),
                (
                    "Across random proper rotations, north/south and east/west sign "
                    f"accuracies were both {number(values['proper_rotation_north_south_accuracy'])}. "
                    "Under axial reflection, north/south accuracy remained "
                    f"{number(values['reflection_north_south_accuracy'])}, whereas "
                    "east/west agreement was "
                    f"{number(values['reflection_east_west_accuracy'])}. These validation "
                    "results are shown in Supplementary Fig. S1."
                ),
                (
                    "The Monte Carlo sanity check separated axis noise from algebraic "
                    "orientation-label corruption. At zero axis noise and label-corruption "
                    "probabilities of "
                    "0.1 and 0.4, north/south accuracy remained "
                    f"{number(values['north_south_accuracy_at_0.1_chirality_corruption'])}; "
                    "east/west accuracy decreased to "
                    f"{number(values['east_west_accuracy_at_0.1_chirality_corruption'])} "
                    f"(95% Wilson interval "
                    f"{number(values['east_west_accuracy_at_0.1_chirality_corruption_95ci_lower'])}–"
                    f"{number(values['east_west_accuracy_at_0.1_chirality_corruption_95ci_upper'])}) and "
                    f"{number(values['east_west_accuracy_at_0.4_chirality_corruption'])} "
                    f"(95% Wilson interval "
                    f"{number(values['east_west_accuracy_at_0.4_chirality_corruption_95ci_lower'])}–"
                    f"{number(values['east_west_accuracy_at_0.4_chirality_corruption_95ci_upper'])}), "
                    "respectively (Supplementary Fig. S2)."
                ),
                (
                    "The ITRF2020 demonstration selected "
                    f"{int(values['n_selected_sites'])} SLR stations (Fig. 5). "
                    "Distance reconstruction again had negligible reflection-permitting "
                    f"RMSE ({values['distance_reconstruction_rmse_m']:.2e} m). "
                    "A computational reflection preserved all axial-order signs and "
                    "reversed all nondegenerate signed-longitude signs; it is a symmetry "
                    "test, not a physically valid ITRF realization. From "
                    f"{values['reference_epoch']:.1f} to {values['comparison_epoch']:.1f}, "
                    "the maximum absolute pairwise-distance change was "
                    f"{number(values['maximum_pairwise_distance_change_m'])} m and the "
                    "median was "
                    f"{number(values['median_pairwise_distance_change_m'])} m."
                ),
                "__FIGURE_5__",
            ],
        ),
        (
            "6 Discussion",
            [
                (
                    "Why not simply store latitude, longitude, height, epoch, and the "
                    "reference frame? That is the correct operational answer when the "
                    "coordinate metadata, realization, transformation models, and "
                    "software remain available. It is not equivalent to preserving the "
                    "relation under metadata loss. Coordinates encode a chosen "
                    "representation; distances encode frame-free metric information; a "
                    "directed axis and physical chirality encode orientation; and redundant "
                    "physical anchors provide independently testable recovery paths. "
                    "Storing both coordinates and relational invariants is therefore not "
                    "duplication: it permits detection of corruption, convention loss, or "
                    "misapplied transformations."
                ),
                (
                    "The residual-invariance hierarchy complements, rather than replaces, "
                    "free-network adjustment. Datum constraints choose or realize a coordinate "
                    "representation within a gauge class; the present audit asks which "
                    "claims are shared by every member of that class. Helmert alignment, "
                    "minimum constraints, NNT/NNR conditions, and CRS metadata remain "
                    "essential for operational coordinates, but they do not retroactively "
                    "create a lost physical chiral witness or meridian anchor."
                ),
                (
                    "A plate-reconstruction model is likewise insufficient by itself. A "
                    "model represents an interpretation conditioned on plate circuits, "
                    "Euler rotations, paleomagnetic assumptions, hotspot or mantle "
                    "anchors, and a particular absolute-longitude strategy. The model may "
                    "become unavailable or superseded, and its parameters do not replace "
                    "the underlying observations, uncertainty, provenance, or entity "
                    "mapping. Global plate frames seek coherence among such constraints "
                    "(Torsvik et al. 2008), but geological longitude remains more "
                    "model-dependent than paleolatitude (Torsvik et al. 2012; Torsvik and "
                    "Cocks 2019). The "
                    "appropriate archival response is to store model version and outputs "
                    "together with constraints and uncertainty, not to label "
                    "paleolongitude categorically impossible."
                ),
                (
                    "The hierarchy shows why additional anchors should be "
                    "independent. Multiple coordinates derived from the same frame "
                    "operation are correlated copies, not redundant physical evidence. A "
                    "hybrid archive should combine labeled distances, physical "
                    "chirality, directed-axis evidence, epoch/time-scale metadata, and "
                    "provenance whose failure modes are not identical."
                ),
                (
                    "Reference-frame durability is consequently relation-specific. A "
                    "terrestrial frame is precise for modern crust-fixed coordinates but "
                    "depends on maintained stations and motion models. A celestial frame "
                    "offers inertial orientation but requires Earth-orientation links for "
                    "terrestrial directions. A spin-axis frame supports axial ordering "
                    "but not a meridian. Plate-fixed, paleomagnetic, hotspot, and mantle "
                    "frames extend to geological time only through additional physical "
                    "assumptions. Calling any one of these frames 'permanent' without "
                    "naming the preserved relation hides the actual invariance class."
                ),
                (
                    "A machine-readable implementation of E should preserve values, units, "
                    "coordinate and time scales, identifier namespaces, covariance or "
                    "samples, source checksums, model versions, and explicit statements of "
                    "which symmetries remain unresolved. Reconstruction software should "
                    "emit both an estimate and an ambiguity descriptor—for example, "
                    "'unique up to axial reflection'—so later users cannot mistake a "
                    "chosen convention for recovered evidence."
                ),
                (
                    "Entity identity is a separate inverse problem. A perfect frame "
                    "cannot decide whether a historical name denotes a monument, a moving "
                    "plate, a city footprint, or a semantic region. Candidate mappings "
                    "and their probabilities belong in I and U, and spatial reconstruction "
                    "should be conditional on them."
                ),
            ],
        ),
        (
            "7 Limitations",
            [
                (
                    "The formal results assume labeled points, a Euclidean embedding, a "
                    "known metric scale, a recoverable origin for axial projection, and generic "
                    "nondegenerate configurations. Real archives may contain incomplete "
                    "distance graphs, deformation, topological change, scale loss, and "
                    "correlated anchor errors. Surface-geodesic and non-Euclidean distance "
                    "models require separate theorems. Local rigidity rank neither proves "
                    "global uniqueness nor solves graph completion and identity inference."
                ),
                (
                    "The ITRF example demonstrates symmetry and epoch sensitivity in a "
                    "modern realized network. It does not validate million-year station "
                    "propagation, plate reconstructions, paleomagnetic field models, or "
                    "mantle frames. Linear station velocities over ten years are used only "
                    "to make the epoch dependence directly auditable."
                ),
                (
                    "A meridian or chiral witness can be physically defined in several "
                    "ways, but recoverability, independence, uncertainty, and deformation "
                    "must be assessed for each application. Paleolongitude remains model-"
                    "dependent, and neither the hierarchy nor the ITRF demonstration "
                    "validates a particular deep-time reconstruction mechanism."
                ),
            ],
        ),
        (
            "8 Conclusions",
            [
                (
                    "Preserving historical direction requires more than preserving "
                    "coordinates or distances. Complete distances preserve metric shape "
                    "up to orthogonal gauge freedom. A directed physical axis supports "
                    "axial ordering, a recoverable physical chiral witness supports signed "
                    "relative longitude, and a directed meridian supports absolute angular "
                    "origin. Epoch, entity identity, metric scale, uncertainty, and "
                    "provenance are independent requirements."
                ),
                (
                    "A practical archive should therefore retain the original coordinate "
                    "representation and frame metadata, relational invariants, orientation "
                    "anchors, explicit epochs, uncertainty, and provenance. The correct "
                    "output when information is missing is an ambiguity class or "
                    "probability—not an unjustified unique reconstruction."
                ),
            ],
        ),
    ]
    return abstract, sections


def build_manuscript(values: dict[str, float]) -> None:
    document = Document()
    style_document(document)
    add_title_page(document)
    abstract, sections = manuscript_sections(values)
    captions = figure_captions(values)
    abstract_word_count = len(abstract.split())
    if not 150 <= abstract_word_count <= 250:
        raise ValueError(f"Abstract has {abstract_word_count} words")
    document.add_heading("Abstract", level=1)
    document.add_paragraph(abstract)
    document.add_paragraph(
        "Keywords: geodetic datum; reference frame; identifiability; distance geometry; "
        "rigidity; epoch"
    )
    table_1 = pd.read_csv(TABLES / "table_1_identifiability_hierarchy.csv")
    table_2 = pd.read_csv(TABLES / "table_2_reference_frame_taxonomy.csv")
    table_3 = pd.read_csv(TABLES / "table_3_rigidity_thresholds.csv")
    body_fragments = []
    for heading, paragraphs in sections:
        document.add_heading(heading, level=1)
        for text in paragraphs:
            if text == "__FIGURE_1__":
                add_figure(document, 1, captions)
            elif text == "__FIGURE_2__":
                add_figure(document, 2, captions)
            elif text == "__FIGURE_3__":
                add_figure(document, 3, captions)
            elif text == "__FIGURE_4__":
                add_figure(document, 4, captions)
            elif text == "__FIGURE_5__":
                add_figure(document, 5, captions)
            elif text == "__TABLE_1__":
                add_dataframe_table(
                    document,
                    table_1,
                    1,
                    "Information hierarchy and residual ambiguity under a rigid model.",
                )
            elif text == "__TABLE_2__":
                add_landscape_section(document)
                add_dataframe_table(
                    document,
                    table_2,
                    2,
                    "Reference-frame classes, physical anchors, and principal failure modes.",
                )
                add_portrait_section(document)
            elif text == "__TABLE_3__":
                add_dataframe_table(
                    document,
                    table_3,
                    3,
                    "First tested edge-retention probabilities with observed local-rigidity "
                    "frequencies at or above 0.50 and 0.95 in the seeded generic-random-"
                    "framework experiment; these are not universal thresholds.",
                )
            else:
                document.add_paragraph(text)
                body_fragments.append(text)
    document.add_heading("Declarations", level=1)
    document.add_heading("Funding", level=2)
    document.add_paragraph(
        "[To be completed locally before submission.]"
    )
    document.add_heading("Competing interests", level=2)
    document.add_paragraph(
        "[To be completed locally before submission.]"
    )
    document.add_heading("Author contributions", level=2)
    document.add_paragraph(AUTHOR_CONTRIBUTIONS)
    document.add_heading("Data availability", level=2)
    document.add_paragraph(DATA_AVAILABILITY)
    document.add_heading("Code availability", level=2)
    document.add_paragraph(CODE_AVAILABILITY)
    document.add_heading("Ethics approval", level=2)
    document.add_paragraph(
        "Not applicable. The study uses synthetic geometry and public geodetic station "
        "products and involves no human participants or animals."
    )
    document.add_heading("Generative AI disclosure", level=2)
    document.add_paragraph(AI_DISCLOSURE)
    document.add_heading("References", level=1)
    references = [
        (
            "Altamimi Z, Sillard P, Boucher C (2002) ITRF2000: a new release of the "
            "International Terrestrial Reference Frame for earth science applications. "
            "Journal of Geophysical Research: Solid Earth 107(B10):ETG 2-1–ETG 2-19. "
            "https://doi.org/10.1029/2001JB000561"
        ),
        (
            "Altamimi Z, Sillard P, Boucher C (2003) The impact of a no-net-rotation "
            "condition on ITRF2000. Geophysical Research Letters 30(2):1064. "
            "https://doi.org/10.1029/2002GL016279"
        ),
        (
            "Altamimi Z, Rebischung P, Collilieux X, Métivier L, Chanard K (2023) "
            "ITRF2020: an augmented reference frame refining the modeling of nonlinear "
            "station motions. Journal of Geodesy 97:47. "
            "https://doi.org/10.1007/s00190-023-01738-w"
        ),
        (
            "Asimow L, Roth B (1978) The rigidity of graphs. Transactions of the "
            "American Mathematical Society 245:279–289. "
            "https://doi.org/10.1090/S0002-9947-1978-0511410-9"
        ),
        (
            "Asimow L, Roth B (1979) The rigidity of graphs, II. Journal of Mathematical "
            "Analysis and Applications 68:171–190. "
            "https://doi.org/10.1016/0022-247X(79)90108-2"
        ),
        (
            "Bevis M, Brown A (2014) Trajectory models and reference frames for crustal "
            "motion geodesy. Journal of Geodesy 88:283–311. "
            "https://doi.org/10.1007/s00190-013-0685-5"
        ),
        (
            "Chatzinikos M, Dermanis A (2017) A coordinate-invariant model for deforming "
            "geodetic networks: understanding rank deficiencies, non-estimability of "
            "parameters, and the effect of the choice of minimal constraints. Journal of "
            "Geodesy 91:375–396. https://doi.org/10.1007/s00190-016-0970-1"
        ),
        (
            "Dokmanić I, Parhizkar R, Ranieri J, Vetterli M (2015) Euclidean distance "
            "matrices: essential theory, algorithms, and applications. IEEE Signal "
            "Processing Magazine 32(6):12–30. "
            "https://doi.org/10.1109/MSP.2015.2398954"
        ),
        (
            "Glaser S, Fritsche M, Sośnica K et al (2015) A consistent combination of "
            "GNSS and SLR with minimum constraints. Journal of Geodesy 89:1165–1180. "
            "https://doi.org/10.1007/s00190-015-0842-0"
        ),
        (
            "International Organization for Standardization (2019) ISO 19111:2019 "
            "Geographic information—Referencing by coordinates. ISO, Geneva. "
            "https://www.iso.org/standard/74039.html"
        ),
        (
            "Kabsch W (1976) A solution for the best rotation to relate two sets of "
            "vectors. Acta Crystallographica Section A 32:922–923. "
            "https://doi.org/10.1107/S0567739476001873"
        ),
        (
            "Kabsch W (1978) A discussion of the solution for the best rotation to "
            "relate two sets of vectors. Acta Crystallographica Section A 34:827–828. "
            "https://doi.org/10.1107/S0567739478001680"
        ),
        (
            "Kotsakis C (2012) Reference frame stability and nonlinear distortion in "
            "minimum-constrained network adjustment. Journal of Geodesy 86:755–774. "
            "https://doi.org/10.1007/s00190-012-0555-6"
        ),
        (
            "Kotsakis C (2013) Generalized inner constraints for geodetic network "
            "densification problems. Journal of Geodesy 87:661–673. "
            "https://doi.org/10.1007/s00190-013-0637-0"
        ),
        (
            "Kotsakis C, Chatzinikos M (2017) Rank defect analysis and the realization "
            "of proper singularity in normal equations of geodetic networks. Journal of "
            "Geodesy 91:627–652. https://doi.org/10.1007/s00190-016-0989-3"
        ),
        (
            "Liberti L, Lavor C, Maculan N, Mucherino A (2014) Euclidean distance "
            "geometry and applications. SIAM Review 56(1):3–69. "
            "https://doi.org/10.1137/120875909"
        ),
        (
            "Moritz H (2000) Geodetic Reference System 1980. Journal of Geodesy "
            "74:128–133. https://doi.org/10.1007/s001900050278"
        ),
        (
            "Papo HB (1985) Extended free net adjustment constraints. Bulletin "
            "Géodésique 59:378–390. https://doi.org/10.1007/BF02521070"
        ),
        (
            "Petit G, Luzum B (eds) (2010) IERS Conventions (2010). IERS Technical "
            "Note 36. https://iers-conventions.obspm.fr/content/tn36.pdf"
        ),
        (
            "Sillard P, Boucher C (2001) A review of algebraic constraints in terrestrial "
            "reference frame datum definition. Journal of Geodesy 75:63–73. "
            "https://doi.org/10.1007/S001900100166"
        ),
        (
            "Torsvik TH, Müller RD, Van der Voo R, Steinberger B, Gaina C (2008) "
            "Global plate motion frames: toward a unified model. Reviews of Geophysics "
            "46:RG3004. https://doi.org/10.1029/2007RG000227"
        ),
        (
            "Torsvik TH, Van der Voo R, Preeden U et al (2012) Phanerozoic polar "
            "wander, palaeogeography and dynamics. Earth-Science Reviews 114:325–368. "
            "https://doi.org/10.1016/j.earscirev.2012.06.007"
        ),
        (
            "Torsvik TH, Cocks LRM (2019) The integration of palaeomagnetism, the "
            "geological record and mantle tomography in the location of ancient "
            "continents. Geological Magazine 156:242–260. "
            "https://doi.org/10.1017/S001675681700098X"
        ),
        (
            "Zajdel R, Sośnica K, Drożdżewski M, Bury G, Strugarek D (2019) Impact of "
            "network constraining on the terrestrial reference frame realization based "
            "on SLR observations to LAGEOS. Journal of Geodesy 93:2293–2313. "
            "https://doi.org/10.1007/s00190-019-01307-0"
        ),
    ]
    for reference in references:
        add_reference(document, reference)
    body = "\n".join(body_fragments)
    figure_positions = [body.find(f"Fig. {index}") for index in range(1, 6)]
    table_positions = [body.find(f"Table {index}") for index in range(1, 4)]
    if any(position < 0 for position in figure_positions + table_positions):
        raise ValueError("Every figure and table must be cited in body text")
    if figure_positions != sorted(figure_positions) or table_positions != sorted(table_positions):
        raise ValueError("Figure and table citations must be sequential")
    document.save(MANUSCRIPT / "manuscript.docx")


def build_editable_tables() -> None:
    document = Document()
    style_document(document)
    document.add_heading("Editable tables", level=0)
    add_dataframe_table(
        document,
        pd.read_csv(TABLES / "table_1_identifiability_hierarchy.csv"),
        1,
        "Information hierarchy and residual ambiguity under a rigid model.",
    )
    document.add_page_break()
    add_dataframe_table(
        document,
        pd.read_csv(TABLES / "table_2_reference_frame_taxonomy.csv"),
        2,
        "Reference-frame classes, physical anchors, and principal failure modes.",
    )
    document.add_page_break()
    add_dataframe_table(
        document,
        pd.read_csv(TABLES / "table_3_rigidity_thresholds.csv"),
        3,
        "Seeded local-rigidity transition summary for generic random frameworks.",
    )
    document.save(MANUSCRIPT / "tables.docx")


def build_editable_figures(values: dict[str, float]) -> None:
    presentation = Presentation()
    presentation.slide_width = PptxInches(13.333)
    presentation.slide_height = PptxInches(7.5)
    captions = figure_captions(values)
    figures = [
        ("Figure 1", "figure_1_representation_hierarchy.png", captions[0]),
        ("Figure 2", "figure_2_residual_invariance_hierarchy.png", captions[1]),
        ("Figure 3", "figure_3_direction_asymmetry.png", captions[2]),
        ("Figure 4", "figure_4_rigidity_phase_diagram.png", captions[3]),
        ("Figure 5", "figure_5_itrf_demonstration.png", captions[4]),
        (
            "Supplementary Figure S1",
            "supplementary_figure_s1_synthetic_benchmark.png",
            "Synthetic theorem-validation benchmark under proper rotation and axial reflection.",
        ),
        (
            "Supplementary Figure S2",
            "supplementary_figure_s2_anchor_sensitivity.png",
            "Seeded axis-noise and algebraic-orientation-corruption validation experiment.",
        ),
    ]
    for label, name, figure_caption in figures:
        slide = presentation.slides.add_slide(presentation.slide_layouts[6])
        title_box = slide.shapes.add_textbox(
            PptxInches(0.5), PptxInches(0.2), PptxInches(12.33), PptxInches(0.55)
        )
        title = title_box.text_frame.paragraphs[0]
        title.text = label
        title.font.name = "Arial"
        title.font.size = PptxPt(22)
        title.font.bold = True
        title.alignment = PP_ALIGN.CENTER
        slide.shapes.add_picture(
            str(FIGURES / name),
            PptxInches(1.2),
            PptxInches(0.85),
            width=PptxInches(10.93),
            height=PptxInches(5.6),
        )
        caption_box = slide.shapes.add_textbox(
            PptxInches(0.6), PptxInches(6.5), PptxInches(12.13), PptxInches(0.75)
        )
        caption = caption_box.text_frame.paragraphs[0]
        caption.text = figure_caption
        caption.font.name = "Arial"
        caption.font.size = PptxPt(11)
    presentation.save(MANUSCRIPT / "figures.pptx")


def build_supplement(values: dict[str, float]) -> None:
    document = Document()
    style_document(document)
    document.add_heading("Supplementary information", level=0)
    document.add_paragraph(TITLE)
    document.add_heading("S1 Formal assumptions and degeneracies", level=1)
    document.add_paragraph(
        "The distance result assumes a labeled Euclidean distance matrix of embedding "
        "dimension at most three. Sparse graphs may admit flexes or multiple discrete "
        "realizations. Repeated points, collinear or coplanar simplices, axis-pole "
        "locations, and projected antipodes are treated as degeneracies rather than "
        "forced directional classifications."
    )
    document.add_paragraph(
        "Generic axial ordering requires an origin and a directed axis. An undirected "
        "axis leaves its labels exchangeable. Signed relative longitude requires a "
        "physically recoverable chiral witness; absolute angular origin requires an "
        "additional directed meridian. A stored orientation bit without recoverable "
        "physical meaning does not remove the reflection ambiguity."
    )
    document.add_heading("S2 Computational algorithms", level=1)
    document.add_paragraph(
        "Classical multidimensional scaling uses the three largest positive eigenpairs "
        "of the double-centered squared-distance matrix. Procrustes alignment uses a "
        "singular-value decomposition and explicitly constrains the determinant when "
        "reflection is forbidden. Direction signs are evaluated from normalized axial "
        "projections and a two-argument arctangent on the principal branch. The rigidity "
        "analysis uses numerical rank of the three-dimensional rigidity matrix with an "
        "SVD tolerance scaled by matrix dimensions and machine precision."
    )
    document.add_heading("S3 Reproducibility configuration", level=1)
    config = (ROOT / "configs/default.yml").read_text(encoding="utf-8")
    paragraph = document.add_paragraph()
    run = paragraph.add_run(config)
    run.font.name = "Courier New"
    run.font.size = Pt(8)
    document.add_heading("S4 ITRF2020 selected stations", level=1)
    sites = pd.read_csv(ROOT / "data/processed/itrf_selected_sites.csv")
    columns = [
        "domes",
        "site_name",
        "technique_id",
        "latitude_degrees",
        "longitude_degrees",
        "reference_epoch",
        "comparison_epoch",
    ]
    add_dataframe_table(
        document,
        sites[columns],
        1,
        "Selected ITRF2020 SLR stations and epochs.",
    )
    document.add_heading("S5 Incomplete-network and ellipsoid sensitivity", level=1)
    add_dataframe_table(
        document,
        pd.read_csv(TABLES / "table_s1_ellipsoid_sensitivity.csv"),
        "S1",
        "WGS84–GRS80 sensitivity for the seeded point set.",
    )
    document.add_paragraph()
    document.add_picture(
        str(FIGURES / "supplementary_figure_s1_synthetic_benchmark.png"),
        width=Inches(6.25),
    )
    document.add_paragraph(
        "Supplementary Fig. S1  Synthetic theorem-validation benchmark. Proper rotations "
        "preserve both tested directional signs; axial reflection preserves axial "
        "ordering and reverses signed longitude."
    )
    document.add_picture(
        str(FIGURES / "supplementary_figure_s2_anchor_sensitivity.png"),
        width=Inches(6.25),
    )
    document.add_paragraph(
        "Supplementary Fig. S2  Seeded axis-noise and algebraic-orientation-corruption "
        "experiment. The curves are conditional simulation checks and are not estimates "
        "of physical anchor survival."
    )
    document.add_heading("S6 Numerical result registry", level=1)
    result_frame = pd.read_csv(ROOT / "results/manuscript_values.csv")
    add_dataframe_table(
        document,
        result_frame,
        "S2",
        "Machine-generated values used in the manuscript.",
    )
    document.add_heading("S7 Test coverage", level=1)
    document.add_paragraph(
        "The automated suite covers rigid-transform distance invariance, independent "
        "proper and reflection-permitting alignment, simplex chirality, local ENU basis "
        "orthonormality, proper-rotation direction invariance, axial-reflection direction "
        "asymmetry, branch wrapping, same-meridian ties, pole and exact/near-antipode "
        "degeneracies, rigidity rank, ITRF parsing and site count, "
        "configuration-dependent epoch labels, nondefault uncertainty grids, and seeded "
        "reproducibility."
    )
    document.add_heading("S8 Interpretation of main numerical values", level=1)
    document.add_paragraph(
        f"The proper-only mirror ambiguity is "
        f"{number(values['distance_reconstruction_rmse_proper_only_m'] / 1e6, 3)} "
        "million m for the seeded point set. This value characterizes the selected "
        "configuration and is not a universal Earth-scale constant."
    )
    document.add_paragraph(
        "The local-rigidity frequencies are Monte Carlo summaries for independently "
        "sampled generic points and Bernoulli edge retention. They do not establish "
        "global rigidity, geodetic network optimality, or a universal density threshold."
    )
    document.save(SUPPLEMENT / "supplement.docx")


def build_cover_letter() -> None:
    document = Document()
    style_document(document)
    document.add_paragraph("Editor-in-Chief")
    document.add_paragraph("Journal of Geodesy")
    document.add_paragraph()
    document.add_paragraph("Dear Editor-in-Chief,")
    document.add_paragraph(
        f"Please consider my Original Research Article, “{TITLE},” for publication "
        "in Journal of Geodesy."
    )
    document.add_paragraph(
        "The manuscript addresses a geodetic identifiability question that is distinct "
        "from, but complementary to, free-network adjustment and datum realization: "
        "which spatial relations remain invariant when datum, reference-frame, or epoch "
        "metadata is no longer recoverable? It expresses the answer through the residual "
        "invariance-group chain O(3) to O(2) to SO(2) to the identity."
    )
    document.add_paragraph(
        "The analysis distinguishes a directed physical axis, a physically recoverable "
        "chiral witness, and a directed meridian; it also defines directional branch and "
        "degeneracy cases explicitly. Seeded incomplete-network rigidity analysis, "
        "ellipsoid sensitivity, and an official ITRF2020 SLR epoch demonstration provide "
        "quantitative tests without presenting a reflected network as a physical "
        "realization. The topic is directly relevant to datum defect, frame realization, "
        "time-dependent geodetic networks, and durable coordinate metadata."
    )
    document.add_paragraph(
        "The work uses synthetic geometry and public geodetic products and involves no "
        "human participants or animals. The editable manuscript, figures, tables, "
        "supplement, persisted public inputs, checksums, code, tests, and result "
        "traceability accompany the submission."
    )
    document.add_paragraph("Sincerely,")
    document.add_paragraph(AUTHOR)
    document.add_paragraph(AFFILIATION)
    document.add_paragraph(EMAIL)
    document.save(SUBMISSION / "cover_letter.docx")


def build_title_page() -> None:
    manuscript = Document(MANUSCRIPT / "manuscript.docx")
    manuscript_word_count = sum(
        len(paragraph.text.split()) for paragraph in manuscript.paragraphs
    )
    document = Document()
    style_document(document)
    add_title_page(document)
    document.add_heading("Article information", level=1)
    document.add_paragraph(f"Short title: {SHORT_TITLE}")
    document.add_paragraph("Article type: Original Research Article")
    document.add_paragraph(
        "Keywords: geodetic datum; reference frame; identifiability; distance geometry; "
        "rigidity; epoch"
    )
    document.add_paragraph("ORCID: [to be confirmed]")
    document.add_paragraph(
        f"Manuscript word count (including declarations and references): "
        f"{manuscript_word_count:,}"
    )
    document.save(SUBMISSION / "title_page.docx")


def build_declarations() -> None:
    document = Document()
    style_document(document)
    document.add_heading("Declarations", level=0)
    statements = [
        (
            "Funding",
            "[To be completed locally before submission.]",
        ),
        (
            "Competing interests",
            "[To be completed locally before submission.]",
        ),
        (
            "Ethics approval",
            "Not applicable; no human participants or animals were involved.",
        ),
        (
            "Consent to participate",
            "Not applicable.",
        ),
        (
            "Consent for publication",
            "Not applicable.",
        ),
        (
            "Data availability",
            DATA_AVAILABILITY,
        ),
        (
            "Code availability",
            CODE_AVAILABILITY,
        ),
        (
            "Author contributions",
            AUTHOR_CONTRIBUTIONS,
        ),
        (
            "Generative AI disclosure",
            AI_DISCLOSURE,
        ),
    ]
    for heading, statement in statements:
        document.add_heading(heading, level=1)
        document.add_paragraph(statement)
    document.save(SUBMISSION / "declarations.docx")


def convert_to_pdf(source: Path, output_directory: Path) -> None:
    subprocess.run(
        [
            "libreoffice",
            "--headless",
            "--convert-to",
            "pdf",
            "--outdir",
            str(output_directory),
            str(source),
        ],
        check=True,
        capture_output=True,
        text=True,
    )


def build_reproducibility_archive() -> Path:
    archive = SUBMISSION / "dtrs_reproducibility.zip"
    explicit_files = [
        ROOT / "Makefile",
        ROOT / "pyproject.toml",
        ROOT / "README.md",
        ROOT / "DATA_PROVENANCE.md",
        ROOT / "DECISIONS.md",
        ROOT / "JOURNAL_REQUIREMENTS_AUDIT.md",
        ROOT / "NOVELTY_AUDIT.md",
        ROOT / "THEOREM_AUDIT.md",
        ROOT / "TERMINOLOGY_FINAL_AUDIT.md",
        ROOT / "RIGIDITY_REPLICATION_AUDIT.md",
        ROOT / "REFERENCE_VERIFICATION_AUDIT.md",
        ROOT / "PLACEHOLDER_FINAL_AUDIT.md",
        ROOT / "AI_POLICY_AUDIT.md",
        ROOT / "FINAL_MINOR_REVIEW.md",
        ROOT / "FINAL_REPRODUCIBILITY_REPORT.md",
        ROOT / "FINAL_REVISION_REPORT.md",
        ROOT / "FINAL_USER_INPUT_REQUIRED.md",
        ROOT / "DATA_CODE_AVAILABILITY.txt",
        ROOT / "AI_DISCLOSURE.txt",
        ROOT / "RESULT_CHANGELOG.md",
        ROOT / "SUBMISSION_CHECKLIST.md",
        ROOT / "references_verified.csv",
        ROOT / "result_traceability.csv",
        ROOT / "data/data_acquisition_log.csv",
    ]
    patterns = [
        "configs/*.yml",
        "src/**/*.py",
        "scripts/*.py",
        "tests/*.py",
        "data/raw/itrf2020/*",
        "data/raw/literature/*.json",
        "data/processed/*.csv",
        "results/*.csv",
        "figures/*.png",
        "tables/*.csv",
    ]
    files = list(explicit_files)
    for pattern in patterns:
        files.extend(sorted(ROOT.glob(pattern)))
    with zipfile.ZipFile(archive, "w", compression=zipfile.ZIP_DEFLATED) as handle:
        for path in dict.fromkeys(files):
            handle.write(path, path.relative_to(ROOT))
    return archive


def copy_submission_files() -> list[Path]:
    if SUBMISSION_FINAL.exists():
        shutil.rmtree(SUBMISSION_FINAL)
    (SUBMISSION_FINAL / "figures").mkdir(parents=True)
    (SUBMISSION_FINAL / "tables").mkdir()
    copies = [
        (MANUSCRIPT / "manuscript.docx", "manuscript_inline.docx"),
        (MANUSCRIPT / "manuscript.pdf", "manuscript.pdf"),
        (MANUSCRIPT / "figures.pptx", "figures_editable.pptx"),
        (MANUSCRIPT / "tables.docx", "tables_editable.docx"),
        (SUPPLEMENT / "supplement.docx", "supplement.docx"),
        (SUPPLEMENT / "supplement.pdf", "supplement.pdf"),
        (SUBMISSION / "cover_letter.docx", "cover_letter.docx"),
        (SUBMISSION / "title_page.docx", "title_page.docx"),
        (SUBMISSION / "declarations.docx", "declarations.docx"),
        (SUBMISSION / "dtrs_reproducibility.zip", "dtrs_reproducibility.zip"),
        (ROOT / "FINAL_SUBMISSION_README.md", "FINAL_SUBMISSION_README.md"),
        (ROOT / "SUBMISSION_CHECKLIST.md", "AUTHOR_CHECKLIST.md"),
        (ROOT / "FINAL_USER_INPUT_REQUIRED.md", "FINAL_USER_INPUT_REQUIRED.md"),
        (ROOT / "DATA_CODE_AVAILABILITY.txt", "DATA_CODE_AVAILABILITY.txt"),
        (ROOT / "AI_DISCLOSURE.txt", "AI_DISCLOSURE.txt"),
    ]
    files = []
    for source, name in copies:
        destination = SUBMISSION_FINAL / name
        shutil.copy2(source, destination)
        files.append(destination)
    figure_names = [
        "figure_1_representation_hierarchy.png",
        "figure_2_residual_invariance_hierarchy.png",
        "figure_3_direction_asymmetry.png",
        "figure_4_rigidity_phase_diagram.png",
        "figure_5_itrf_demonstration.png",
        "supplementary_figure_s1_synthetic_benchmark.png",
        "supplementary_figure_s2_anchor_sensitivity.png",
    ]
    for name in figure_names:
        destination = SUBMISSION_FINAL / "figures" / name
        shutil.copy2(FIGURES / name, destination)
        files.append(destination)
    for table in sorted(TABLES.glob("table_*.csv")):
        destination = SUBMISSION_FINAL / "tables" / table.name
        shutil.copy2(table, destination)
        files.append(destination)
    return files


def build_manifest_and_zip(files: list[Path]) -> None:
    manifest_path = SUBMISSION_FINAL / "MANIFEST.csv"
    with manifest_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle, lineterminator="\n")
        writer.writerow(["file", "size_bytes", "sha256"])
        for path in files:
            writer.writerow(
                [path.relative_to(SUBMISSION_FINAL), path.stat().st_size, sha256(path)]
            )
    archive = SUBMISSION / "journal_of_geodesy_submission_FINAL.zip"
    with zipfile.ZipFile(archive, "w", compression=zipfile.ZIP_DEFLATED) as handle:
        for path in files + [manifest_path]:
            handle.write(path, path.relative_to(SUBMISSION_FINAL))


def main() -> None:
    for directory in [
        MANUSCRIPT,
        SUPPLEMENT,
        SUBMISSION,
    ]:
        directory.mkdir(parents=True, exist_ok=True)
    values = metric_values()
    build_manuscript(values)
    build_editable_tables()
    build_editable_figures(values)
    build_supplement(values)
    build_cover_letter()
    build_title_page()
    build_declarations()
    convert_to_pdf(MANUSCRIPT / "manuscript.docx", MANUSCRIPT)
    convert_to_pdf(SUPPLEMENT / "supplement.docx", SUPPLEMENT)
    build_reproducibility_archive()
    files = copy_submission_files()
    build_manifest_and_zip(files)
    print(
        "Built submission archive: "
        f"{SUBMISSION / 'journal_of_geodesy_submission_FINAL.zip'}"
    )


if __name__ == "__main__":
    main()
